# Generated by Django 4.1 on 2022-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('washing_date', models.DateField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('ampm', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
