# Generated by Django 4.1 on 2022-12-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
