# Generated by Django 4.1 on 2022-12-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_feedbacks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedbacks',
            table='feedbacks',
        ),
    ]
