# Generated by Django 4.1 on 2022-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.BigIntegerField()),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_dob', models.DateField()),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_idproof', models.CharField(max_length=100)),
                ('emp_idproofnum', models.BigIntegerField()),
                ('emp_photo', models.ImageField(upload_to='profile_images')),
                ('emp_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
